#!/usr/bin/env bash
# Render /opt/athan/web/config.js from /etc/default/athan so the web page and the
# adhan scheduler always use the same location and calculation settings.
set -euo pipefail
CONF=/etc/default/athan
WEB=/opt/athan/web
[ -f "$CONF" ] || { echo "Missing $CONF (copy athan.conf.example there first)"; exit 1; }
# shellcheck source=/dev/null
. "$CONF"

LANGS_JSON=""
for l in ${TRANSLATION_LANGS:-en ur bn}; do LANGS_JSON="${LANGS_JSON}\"${l}\","; done
LANGS_JSON="[${LANGS_JSON%,}]"

cat > "$WEB/config.js" <<JS
// Generated by apply-config.sh from $CONF on $(date '+%F %T') -- edit $CONF, not this file.
window.ATHAN_CONFIG = {
  latitude: ${LATITUDE},
  longitude: ${LONGITUDE},
  method: ${METHOD:-2},
  school: ${SCHOOL:-0},
  tune: "${TUNE:-}",
  langs: ${LANGS_JSON},
  news: ${NEWS_TICKER:-true},
  usNews: ${US_NEWS_TICKER:-true},
  usNewsLabel: "${US_NEWS_LABEL:-NYC LOCAL}",
  weather: ${WEATHER:-true}
};
JS
chmod 644 "$WEB/config.js"
echo "Wrote $WEB/config.js. Reload the display with: systemctl restart lightdm"
